### ISSUE TITLE
Syntax error occurs in AWS Alexa

### ISSUE THREAD

**Issue by GeoffState** [maugenst/tabletojson#29] opened 2018-06-10 23:01 UTC
I can run my code in node command line successfully but when I try to integrate it in an Alexa skill I get a syntax error the moment I require it. 
![tabletojson-lambda](https://user-images.githubusercontent.com/7799948/41207249-5d4655a8-6d66-11e8-8175-bf839208291e.png)
Screen dump is a fully working basic Alexa skill until I add the require('tabletojson'); I have spent hours trying to figure this out and finally have to come to the author for help.

**Comment by maugenst** [comment] 2018-06-11 04:59
Hi. 
While reading through this thread:
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/283

I stumble across the following sentence
" I think i was importing it correctly but I wasnt adding them to the registerHandlers correctly. If you put them in a list first and add the list it doesnt work, "

I'm not familiar with Alexa, but it seems that the module is not correctly registered.
Could this also be the problem here?
Please do me a favor and try this. If the problem still exists get back to me. 
Thanks, Marius

**Comment by pwespi** [comment] 2018-07-06 20:20
I'm getting the same error in Firebase functions. I think the reason is that Firebase functions is running node v6, which does not support async/await. It might be the same issue for AWS Alexa

**Comment by GeoffState** [comment] 2018-07-11 02:37
Sorry, I have been away. Back to the problem. I get this from https://console.aws.amazon.com/lambda/home......

Syntax error in module 'index': SyntaxError
    static async convertUrl(url, arg1, arg2) {
                 ^^^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/task/index.js:18:19)

Code snippet from my index.js

_tabletojson.convertUrl(
  'https://home.nzcity.co.nz/tvnow/default.aspx?ch=1&t=#onnow',
  function(tablesAsJson) {
//    for (var i = 0, len = tablesAsJson[6].length; i < len; i++) {
//      saveProg(tablesAsJson[6][i]);
//    }
    }
);_

**Comment by GeoffState** [comment] 2018-07-11 03:17
Using your example-1.js in AWS 
![2018-07-11_1513_example-1-js](https://user-images.githubusercontent.com/7799948/42548882-75ea9172-851d-11e8-82f5-d84aef5f34ee.png)
Cloud9 environment

**Comment by maugenst** [comment] 2018-07-11 05:37
The problem ist that you are using node6. The native async/await support in node is just available since node 7.6.

Nonetheless I'm currently working on an implementation that builds a es5 dist version of the library. So it then will be usable on all node versions supporting es5 javascript code. I think this is going to be available in the next few days. Hope this helps and thank you very much for your detailed analysis.

CU, Marius

**Comment by GeoffState** [comment] 2018-07-11 05:43
Brilliant thanks!

 

I wonder if I can install later node on cloud9. Something for ME to try.

 

Best Regards
Geoff

**Comment by maugenst** [comment] 2018-07-18 08:38
Hi Geoff 

Just a short update... By fiddling around using Babel to convert my class into es5 syntax I found the converted code not very stable. While trying to not drop the test coverage I tried to rewrite my tests also to es6 and here I'm stuck right now. 

Nonetheless I would like to ask you if you had the chance to update your lambda config to use node 8+ as described here: https://aws.amazon.com/about-aws/whats-new/2018/04/aws-lambda-supports-nodejs/ 

CU, Marius

**Comment by GeoffState** [comment] 2018-07-18 23:42
Hi Marius

 

Yes I could get lambda environment of my choice as per link but I was having trouble getting my cloud9 debugging environment to persist between sessions. Node version is changed per https://community.c9.io/t/how-to-update-node-js/1273/2

 

I attacked it again today and it seems to be persisting now, interesting. I’ll keep you updated.

 

It was interesting to note that Amazon AWS went to the dogs for a couple of hours on Amazon Prime Sale day. I couldn’t get into Alexa console or AWS development consoles.

https://www.zdnet.com/article/wth-amazon/

 

 

Best Regards
Geoff

**Comment by maugenst** [comment] 2018-12-10 13:47
Hi Geoff
I recently ran into the problem that converting my code into vanilla js code was not able to run properly. So I decided to withdraw my proposal to implement this without new syntax features. I will close this thread since aws support node 8+ in all regions. Hope you are ok whith this decission.If not please get back to me.
Thanks, Marius

**Closed by maugenst** 2018-12-10 13:47 UTC

**Comment by GeoffState** [comment] 2018-12-10 20:15
Thanks
